# Generated by Django 5.1.7 on 2025-05-08 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_sum', models.FloatField()),
                ('rooms_sum', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('localisation', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('developer_name', models.CharField(max_length=100)),
                ('developer_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('apartment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentVisualization.apartment_model')),
            ],
        ),
    ]
